In [6]:
from tensorflow.keras.preprocessing.text import one_hot


In [11]:
### sentences
sent=[ 'the glass of milk',
'the glass of juice',
'the cup of tea',
'I am a good boy',
'I am a good developer',
'understand the meaning of words',
'your videos are good',]

In [12]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [21]:
## Define the vocabulary size
voc_size=10000

In [22]:
## One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[979, 8344, 293, 7466],
 [979, 8344, 293, 4138],
 [979, 2183, 293, 3889],
 [1906, 750, 4292, 3868, 8113],
 [1906, 750, 4292, 3868, 6391],
 [4933, 979, 1470, 293, 1312],
 [3309, 7805, 5266, 3868]]

In [23]:
## Word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [24]:
import numpy as np

In [25]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  979 8344  293 7466]
 [   0    0    0    0  979 8344  293 4138]
 [   0    0    0    0  979 2183  293 3889]
 [   0    0    0 1906  750 4292 3868 8113]
 [   0    0    0 1906  750 4292 3868 6391]
 [   0    0    0 4933  979 1470  293 1312]
 [   0    0    0    0 3309 7805 5266 3868]]


In [26]:
## feature representation
dim=10

In [29]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.build(input_shape=(None, sent_length))
model.compile('adam','mse')

In [30]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [31]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 5s 5s/step


array([[[-0.04221521,  0.00799632,  0.02515132,  0.02757834,
         -0.03157695, -0.01452305, -0.02100828,  0.00500733,
         -0.00516622,  0.0326714 ],
        [-0.04221521,  0.00799632,  0.02515132,  0.02757834,
         -0.03157695, -0.01452305, -0.02100828,  0.00500733,
         -0.00516622,  0.0326714 ],
        [-0.04221521,  0.00799632,  0.02515132,  0.02757834,
         -0.03157695, -0.01452305, -0.02100828,  0.00500733,
         -0.00516622,  0.0326714 ],
        [-0.04221521,  0.00799632,  0.02515132,  0.02757834,
         -0.03157695, -0.01452305, -0.02100828,  0.00500733,
         -0.00516622,  0.0326714 ],
        [ 0.03534358, -0.00039436,  0.00403166, -0.02329725,
         -0.04970352, -0.0002973 ,  0.04643624,  0.015359  ,
         -0.04678379,  0.01088933],
        [-0.04105229, -0.02773048, -0.03537602,  0.00375963,
         -0.01517155,  0.04074893, -0.00948238, -0.0094744 ,
         -0.01543926, -0.04199187],
        [-0.01865838, -0.03171712,  0.02734332,  0.0

In [32]:
embedded_docs[0]

array([   0,    0,    0,    0,  979, 8344,  293, 7466])